# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=50, unique=True)),
                ('translate', models.CharField(max_length=100)),
                ('antonym', models.ManyToManyField(blank=True, related_name='_word_antonym_+', to='vocabulary.Word')),
                ('library', models.ManyToManyField(blank=True, to='library.Library')),
            ],
        ),
    ]
